### ISSUE TITLE
osc log | fails

### ISSUE THREAD

**Issue by mmohring** [openSUSE/osc#814]
Since the fixes in osc log, osc log | command fails with a buffer error

**Comment by mmohring** [comment]
Pyhon log of the failure:

$ osc log | less

Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 64, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 6874, in do_log
    run_pager(log)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 4073, in run_pager
    sys.stdout.buffer.write(message)
  File "/usr/lib/python2.7/site-packages/osc/util/safewriter.py", line 20, in __getattr__
    return getattr(self._writer, name)
AttributeError: 'file' object has no attribute 'buffer'
The last version working was commit e807abbf7c68ce6e04d5b34e6d9d0289942ed97a. I guess has to do with the code fixes for osc log.

**Comment by marcus-h** [comment]
On 2020-06-25 04:54:54 -0700, Martin Mohring wrote:
> $ osc log | less
>
> Traceback (most recent call last):
>   File "/usr/bin/osc", line 41, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 64, in run
>     return prg.main(argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 347, in main
>     return self.cmd(args)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 370, in cmd
>     retval = self.onecmd(argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 504, in onecmd
>     return self._dispatch_cmd(handler, argv)
>   File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
>     return handler(argv[0], opts, *args)
>   File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 6874, in do_log
>     run_pager(log)
>   File "/usr/lib/python2.7/site-packages/osc/core.py", line 4073, in run_pager
>     sys.stdout.buffer.write(message)
>   File "/usr/lib/python2.7/site-packages/osc/util/safewriter.py", line 20, in __getattr__
>     return getattr(self._writer, name)
> AttributeError: 'file' object has no attribute 'buffer'
> The last version working was commit e807abbf7c68ce6e04d5b34e6d9d0289942ed97a. I guess has to do with the code fixes for osc log.
>
I broke it with commit 276d6e2439c8c53c182dbe785b038919e64da9f3 ("Do not use
the chardet module in util.helper.decode_it"). Thinking about a possible
fix...

**Comment by mmohring** [comment]
So this is a python2 issue. Do you still support the EOL python2, and how long ?

**Comment by mmohring** [comment]
I put you patch in. Works fine for me. I did not the whole osc.
