### PR TITLE
fix AttributeError: 'NoneType' object has no attribute 'keys'

### LINKED ISSUE #203: AttributeError: 'NoneType' object has no attribute 'keys'
```
$ rpm -q osc
osc-0.152.0-3.2.noarch
$ osc api '/search/channel/binary?match=[@package="gpg2"+and+@project="SUSE:Channels"+and+not(target/disabled)]'
```

<collection matches="0">

Problematic just now is devel:tools:scm/osc ...

```
$ rpm -q osc
osc-0.154.git20160531.2364a08-519.1.noarch
$ osc -A https://api.suse.de/ api '/search/channel/binary?match=[@package="gpg2"+and+@project="SUSE:Channels"+and+not(target/disabled)]'
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 7309, in do_api
    headers=opts.headers)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 3218, in http_request
    for i in headers.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

I am pretty sure that 0.154.git20160422.8466e49-0 was a working version.

### PR DESCRIPTION
**Pull request by andreasstieger**
Follow-up to c53a768, fix AttributeError: 'NoneType' object has no attribute 'keys'

Fixes #203

### CODE REVIEW

**Comment by andreasstieger** [comment]
Test failures of course also due to c53a7681ef289181b03e1077efbfd246bf1247f6.

**Comment by lethliel** [comment]
As this is over two years old and already commited with commit acbd2c17c7649c825f3afb6593aec8df1e77c6ca I will close this PR now.
