### ISSUE TITLE
osc 0.166.0 lacks attribute 'encode'

### ISSUE THREAD

**Issue by olafhering** [openSUSE/osc#660]
After upgrading osc from 0.165.* to 0.166.0 nothing works anymore, on a SLE_15 system:
````
olaf@bax:~/work/ibs $  ibs co -u home:olh:obs:devel:languages:ocaml:410
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 336, in main
    self.postoptparse()
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 145, in postoptparse
    override_verbose = self.options.verbose)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 899, in get_config
    password = creds_mgr.get_password(url, user)
  File "/usr/lib/python3.6/site-packages/osc/credentials.py", line 97, in get_password
    return self.decode_password(passwd)
  File "/usr/lib/python3.6/site-packages/osc/credentials.py", line 106, in decode_password
    compressed_pw = base64.b64decode(password.encode("ascii"))
AttributeError: 'NoneType' object has no attribute 'encode'
olaf@bax:~/work/ibs $  osc config
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 336, in main
    self.postoptparse()
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 145, in postoptparse
    override_verbose = self.options.verbose)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 899, in get_config
    password = creds_mgr.get_password(url, user)
  File "/usr/lib/python3.6/site-packages/osc/credentials.py", line 97, in get_password
    return self.decode_password(passwd)
  File "/usr/lib/python3.6/site-packages/osc/credentials.py", line 106, in decode_password
    compressed_pw = base64.b64decode(password.encode("ascii"))
AttributeError: 'NoneType' object has no attribute 'encode'
olaf@bax:~/work/ibs $  ibs config --change-password
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 336, in main
    self.postoptparse()
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 145, in postoptparse
    override_verbose = self.options.verbose)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 899, in get_config
    password = creds_mgr.get_password(url, user)
  File "/usr/lib/python3.6/site-packages/osc/credentials.py", line 97, in get_password
    return self.decode_password(passwd)
  File "/usr/lib/python3.6/site-packages/osc/credentials.py", line 106, in decode_password
    compressed_pw = base64.b64decode(password.encode("ascii"))
AttributeError: 'NoneType' object has no attribute 'encode'
````
````
rpm -q --changelog osc | head
* Thu Oct 24 2019 Marco Strigl <marco.strigl@suse.com>
- 0.166.0 (boo#1154972)
  * New password handling backend. Supported password stores:
  - Plaintext password
  - Obfuscated password
....
````

**Comment by olafhering** [comment]
(SLE_15_SP1 actually)

**Comment by nickbroon** [comment]
This issue is also seen on Debian Buster.

**Comment by lethliel** [comment]
> This issue is also seen on Debian Buster.

@nickbroon This happens if you have a passx entry in your oscrc. 
Can you please confirm that you have a passx entry?

**Comment by lethliel** [comment]
@nickbroon @olafhering 

Fix is in git master. Building packages at the moment. Release of 0.166.1 today. Sorry for the inconveniences.

**Comment by nickbroon** [comment]
> > This issue is also seen on Debian Buster.
> 
> @nickbroon This happens if you have a passx entry in your oscrc.
> Can you please confirm that you have a passx entry?

Yes, I had a `passx` in my oscrc files. Is that no longer supported?
Is `credentials_mgr_class' now compulsory in oscrc?
Is 'pass' in oscrc with plaintext password still supported?

**Comment by lethliel** [comment]
> > > This issue is also seen on Debian Buster.
> > 
> > 
> > @nickbroon This happens if you have a passx entry in your oscrc.
> > Can you please confirm that you have a passx entry?
> 
> Yes, I had a `passx` in my oscrc files. Is that no longer supported?
> Is `credentials_mgr_class' now compulsory in oscrc?
> Is 'pass' in oscrc with plaintext password still supported?

old configurations are still supported. (just forgot about the passx entries. My bad)
In new installations credentials_mgr_class is used. Yes.
