### PR TITLE
results --xml causes a stack trace

### PR DESCRIPTION
**Pull request by jnweiger**
Quick hack to make 
<pre>
osc results --xml openSUSE:Tools osc
</pre>
work again, instead of printing a stack trace like this:
<pre>
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/dist-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/dist-packages/osc/commandline.py", line 5056, in do_results
    for xml in get_package_results(**kwargs):
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 5609, in get_package_results
    xml = ''.join(show_results_meta(apiurl, project, package, *args, **kwargs))
TypeError: show_results_meta() got an unexpected keyword argument 'showexcl'
</pre>

The results --xml syntax worked fine with at least osc version 0.153

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2017-05-16 08:49:31 -0700, Jürgen Weigert wrote:
> Quick hack to make 
> <pre>
> osc results --xml openSUSE:Tools osc
> </pre>
> work again, instead of printing a stack trace like this:

Hmm the "quick hack" doesn't look "correct" to me. I just fixed it
in commit 900ee88. For now, "osc results --xml" ignores the
"--show-excluded" option (though, we could support it (actually,
supporting it would be consistent wrt. osc's "non --xml" behavior)).
