### ISSUE TITLE
osc 0.157 Exception AttributeError: "Connection instance has no attribute 'ssl_close_flag'"

### ISSUE THREAD

**Issue by apuls** [openSUSE/osc#274]
Hi everybody,

i'm running osc on Debian Jessie (8) and got an update from 0.156 to 0.157.
After this update the osc tool dosen't work anymore and i get the following error if i try a osc co / up

```
Exception` AttributeError: "Connection instance has no attribute 'ssl_close_flag'" in <bound method Connection.__del__ of <M2Crypto.SSL.Connection.Connection instance at 0x7f87bf0b8cf8>> ignored
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/dist-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/dist-packages/osc/commandline.py", line 4715, in do_update
    prj = Project(arg, progress_obj=self.download_progress)
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 638, in __init__
    self.pacs_available = meta_get_packagelist(self.apiurl, self.name)
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 3340, in meta_get_packagelist
    f = http_GET(u)
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 3297, in http_GET
    def http_GET(*args, **kwargs):    return http_request('GET', *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 3286, in http_request
    fd = urlopen(req, data=data)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/osc/oscssl.py", line 219, in https_open
    h.request(req.get_method(), selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 841, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/osc/oscssl.py", line 270, in connect
    connected = self._connect(addrinfo[0])
  File "/usr/lib/python2.7/dist-packages/osc/oscssl.py", line 253, in _connect
    self.sock = SSL.Connection(self.ssl_ctx, family=family)
TypeError: __init__() got an unexpected keyword argument 'family'
```
Going back to version 0.156 everything goes fine

**Comment by andreas-schwab** [comment]
Same on openSUSE 13.2.

**Comment by apuls** [comment]
Update: Version 0.157.1-202 is working on CentOs 7.3.1611

**Comment by marcus-h** [comment]
Fixed in commit ff19a5f. I think we will release an update soon.
Sorry for the noise...

**Comment by andreasstieger** [comment]
Also [boo#1030178](https://bugzilla.opensuse.org/show_bug.cgi?id=1030178)
